# Generated by Django 6.0.4 on 2026-04-24 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nc', '0001_initial'),
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificacionEficacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('fecha_cierre_proyecto', models.DateField()),
                ('fecha_objetivo', models.DateField(help_text='Fecha en que se debe realizar la verificación (cierre + 90 días)')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('eficaz', 'Eficaz'), ('no_eficaz', 'No Eficaz')], default='pendiente', max_length=15)),
                ('fecha_realizada', models.DateField(blank=True, null=True)),
                ('resultado_descripcion', models.TextField(blank=True)),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='verificacion/%Y/%m/')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('nc_generada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origen_verificacion', to='nc.noconformidad')),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verificacion_eficacia', to='proyectos.proyecto')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verificación de Eficacia',
                'verbose_name_plural': 'Verificaciones de Eficacia',
                'ordering': ['fecha_objetivo'],
            },
        ),
    ]
