# Generated by Django 6.0.4 on 2026-04-24 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nc', '0001_initial'),
        ('om', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10)),
                ('proveedor', models.CharField(blank=True, help_text='Proveedor externo o "Interno"', max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('dias_ejecucion', models.PositiveIntegerField(help_text='Días de ejecución estimados')),
                ('estado', models.CharField(choices=[('por_hacer', 'Por Hacer'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado')], default='por_hacer', max_length=15)),
                ('origen', models.CharField(choices=[('nc', 'No Conformidad'), ('om', 'Oportunidad de Mejora'), ('independiente', 'Independiente')], default='independiente', max_length=15)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('nc', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyecto', to='nc.noconformidad')),
                ('om', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='om.oportunidadmejora')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Subtarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('completada', models.BooleanField(default=False)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('completada_en', models.DateTimeField(blank=True, null=True)),
                ('completada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtareas', to='proyectos.proyecto')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
