# Generated by Django 6.0.4 on 2026-04-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quejareclamo',
            name='acciones_a_tomar',
            field=models.TextField(blank=True, verbose_name='Acciones a tomar'),
        ),
        migrations.AddField(
            model_name='quejareclamo',
            name='detalle_visita_cliente',
            field=models.TextField(blank=True, verbose_name='Detalle visita al cliente'),
        ),
        migrations.AddField(
            model_name='quejareclamo',
            name='envio_mail',
            field=models.BooleanField(default=False, verbose_name='Envío de mail al cliente'),
        ),
        migrations.AddField(
            model_name='quejareclamo',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de cierre'),
        ),
        migrations.AddField(
            model_name='quejareclamo',
            name='quien_recibe',
            field=models.CharField(blank=True, max_length=200, verbose_name='Quién recibe la queja'),
        ),
        migrations.AddField(
            model_name='quejareclamo',
            name='resultado',
            field=models.TextField(blank=True, verbose_name='Resultado'),
        ),
    ]
