# Generated by Django 6.0.4 on 2026-04-26 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_add_sector_fks'),
        ('qr', '0002_add_gestion_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quejareclamo',
            name='area_origen',
        ),
        migrations.AddField(
            model_name='quejareclamo',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qr_sector', to='core.sector', verbose_name='Sector de origen'),
        ),
    ]
