# Generated by Django 6.0.4 on 2026-05-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0003_add_sector_fks'),
        ('om', '0002_add_sector_fks'),
        ('qr', '0003_add_sector_fks'),
    ]

    operations = [
        migrations.AddField(
            model_name='quejareclamo',
            name='nc_relacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qrs_relacionados', to='nc.noconformidad', verbose_name='NC asociada'),
        ),
        migrations.AddField(
            model_name='quejareclamo',
            name='om_asociada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qrs_relacionados', to='om.oportunidadmejora', verbose_name='OM asociada'),
        ),
    ]
