# Generated by Django 6.0.4 on 2026-04-24 19:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OportunidadMejora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('sector', models.CharField(max_length=100)),
                ('descripcion', models.TextField(help_text='Descripción de la oportunidad o sugerencia')),
                ('beneficio_potencial', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10)),
                ('clasificacion', models.CharField(choices=[('mejora_proceso', 'Mejora de Proceso'), ('innovacion', 'Innovación / Mejora Continua'), ('eficiencia', 'Eficiencia Operativa'), ('calidad', 'Calidad'), ('otro', 'Otro')], max_length=30)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En Revisión'), ('aprobada', 'Aprobada'), ('en_implementacion', 'En Implementación'), ('cerrada', 'Cerrada'), ('rechazada', 'Rechazada')], default='borrador', max_length=20)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='om_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oportunidad de Mejora',
                'verbose_name_plural': 'Oportunidades de Mejora',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AdjuntoOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='om/adjuntos/%Y/%m/')),
                ('nombre', models.CharField(max_length=255)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('om', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='om.oportunidadmejora')),
            ],
        ),
    ]
