# Generated by Django 6.0.4 on 2026-04-26 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_add_sector_fks'),
        ('om', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidadmejora',
            name='eficacia',
            field=models.CharField(choices=[('pendiente', 'Pendiente de evaluación'), ('eficaz', 'Eficaz'), ('no_eficaz', 'No Eficaz')], default='pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='oportunidadmejora',
            name='evidencia',
            field=models.TextField(blank=True, verbose_name='Evidencia'),
        ),
        migrations.AddField(
            model_name='oportunidadmejora',
            name='fecha_evaluacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de evaluación'),
        ),
        migrations.AddField(
            model_name='oportunidadmejora',
            name='fecha_implementacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de implementación'),
        ),
        migrations.AddField(
            model_name='oportunidadmejora',
            name='om_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='om_generadas', to='om.oportunidadmejora', verbose_name='OM que originó esta (No Eficaz)'),
        ),
        migrations.AddField(
            model_name='oportunidadmejora',
            name='problema_a_mejorar',
            field=models.TextField(blank=True, verbose_name='Problema a mejorar'),
        ),
        migrations.AddField(
            model_name='oportunidadmejora',
            name='rango_evaluacion',
            field=models.CharField(blank=True, choices=[('1m', '1 mes'), ('3m', '3 meses'), ('6m', '6 meses')], max_length=2, verbose_name='Rango de evaluación'),
        ),
        migrations.AddField(
            model_name='oportunidadmejora',
            name='seguimiento',
            field=models.TextField(blank=True, verbose_name='Seguimiento'),
        ),
        migrations.AlterField(
            model_name='oportunidadmejora',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='om_sector', to='core.sector', verbose_name='Sector'),
        ),
    ]
