# Generated by Django 6.0.4 on 2026-04-24 19:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoConformidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('area', models.CharField(max_length=100)),
                ('id_muestra_lote', models.CharField(blank=True, max_length=100)),
                ('parametro_afectado', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('clasificacion', models.CharField(choices=[('material_no_conforme', 'Material no conforme'), ('proceso', 'Proceso'), ('producto', 'Producto'), ('sistema', 'Sistema'), ('logistica', 'Logística')], max_length=30)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En Revisión'), ('aprobada', 'Aprobada'), ('en_implementacion', 'En Implementación'), ('cerrada', 'Cerrada'), ('rechazada', 'Rechazada')], default='borrador', max_length=20)),
                ('probabilidad', models.PositiveSmallIntegerField(blank=True, help_text='1-5', null=True)),
                ('impacto', models.PositiveSmallIntegerField(blank=True, help_text='1-5', null=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nc_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'No Conformidad',
                'verbose_name_plural': 'No Conformidades',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CincoPorques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('etapa_1', models.TextField(help_text='Problema detectado (se pre-carga desde la NC)')),
                ('etapa_2', models.TextField(blank=True, help_text='¿Por qué? (Why 1)')),
                ('etapa_3', models.TextField(blank=True, help_text='¿Por qué? (Why 2)')),
                ('etapa_4', models.TextField(blank=True, help_text='¿Por qué? (Why 3)')),
                ('etapa_5', models.TextField(blank=True, help_text='¿Por qué? (Why 4)')),
                ('causa_raiz', models.TextField(blank=True, help_text='Causa raíz identificada (Why 5)')),
                ('accion_correctiva', models.TextField(blank=True)),
                ('completo', models.BooleanField(default=False)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('nc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cinco_porques', to='nc.noconformidad')),
            ],
            options={
                'verbose_name': '5 Porqués',
                'verbose_name_plural': '5 Porqués',
            },
        ),
        migrations.CreateModel(
            name='AdjuntoNC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='nc/adjuntos/%Y/%m/')),
                ('nombre', models.CharField(max_length=255)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('nc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='nc.noconformidad')),
            ],
        ),
    ]
