# Generated by Django 6.0.4 on 2026-04-26 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0001_initial'),
        ('om', '0001_initial'),
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noconformidad',
            name='contaminacion_cruzada',
            field=models.BooleanField(default=False, verbose_name='¿Contaminación cruzada?'),
        ),
        migrations.AddField(
            model_name='noconformidad',
            name='descripcion_correccion',
            field=models.TextField(blank=True, help_text='Descripción de la corrección aplicada de inmediato', verbose_name='Corrección inmediata'),
        ),
        migrations.AddField(
            model_name='noconformidad',
            name='eficacia',
            field=models.CharField(choices=[('pendiente', 'Pendiente de evaluación'), ('eficaz', 'Eficaz'), ('no_eficaz', 'No Eficaz')], default='pendiente', max_length=10, verbose_name='Eficacia de la acción'),
        ),
        migrations.AddField(
            model_name='noconformidad',
            name='email_cliente',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail del cliente'),
        ),
        migrations.AddField(
            model_name='noconformidad',
            name='evidencia',
            field=models.TextField(blank=True, help_text='Descripción de la evidencia que demuestra la implementación de la corrección', verbose_name='Evidencia'),
        ),
        migrations.AddField(
            model_name='noconformidad',
            name='nc_origen',
            field=models.ForeignKey(blank=True, help_text='NC previa que generó esta como seguimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nc_generadas', to='nc.noconformidad', verbose_name='NC origen (resultó No Eficaz)'),
        ),
        migrations.AddField(
            model_name='noconformidad',
            name='notificar_cliente',
            field=models.BooleanField(default=False, verbose_name='Notificar al cliente'),
        ),
        migrations.AddField(
            model_name='noconformidad',
            name='obs_contaminacion',
            field=models.TextField(blank=True, verbose_name='Observaciones (contaminación)'),
        ),
        migrations.AddField(
            model_name='noconformidad',
            name='om_relacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nc_relacionadas', to='om.oportunidadmejora', verbose_name='OM asociada'),
        ),
        migrations.AddField(
            model_name='noconformidad',
            name='origen',
            field=models.CharField(choices=[('directo', 'Detección Directa'), ('qr', 'Queja / Reclamo'), ('om', 'Oportunidad de Mejora')], default='directo', help_text='Origen de esta No Conformidad', max_length=10),
        ),
        migrations.AddField(
            model_name='noconformidad',
            name='qr_relacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nc_relacionadas', to='qr.quejareclamo', verbose_name='QyR asociada'),
        ),
        migrations.AddField(
            model_name='noconformidad',
            name='tipo_contaminacion',
            field=models.CharField(blank=True, choices=[('reproceso', 'Reproceso'), ('venta', 'Venta'), ('otros', 'Otros')], max_length=10, verbose_name='Tipo de contaminación'),
        ),
    ]
