# Generated by Django 6.0.4 on 2026-04-26 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_add_sector_fks'),
        ('nc', '0002_noconformidad_contaminacion_cruzada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noconformidad',
            name='area',
        ),
        migrations.AddField(
            model_name='noconformidad',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nc_sector', to='core.sector', verbose_name='Sector'),
        ),
    ]
