# Generated by Django 6.0.4

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0005_noconformidad_campos_cierre_reevaluacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CausaRaizIdentificada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('nombre', models.CharField(help_text='Ej: Error de calibración, Falta de capacitación, Desgaste de equipamiento', max_length=255, unique=True, verbose_name='Nombre de la causa raíz')),
                ('descripcion', models.TextField(blank=True, help_text='Detalle de qué abarca esta causa raíz', verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, help_text='Marcar inactivo para dejar de usarla sin eliminarla', verbose_name='Activo')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Causa Raíz Identificada',
                'verbose_name_plural': 'Causas Raíz Identificadas',
                'ordering': ['nombre'],
            },
        ),
    ]
