# Generated by Django 6.0.4

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0006_add_causaraizidentificada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NormaNC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('nombre', models.CharField(help_text='Ej: ISO 9001:2015, BPM, HACCP', max_length=255, unique=True, verbose_name='Norma')),
                ('descripcion', models.TextField(blank=True, help_text='Detalle opcional para contextualizar la norma', verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, help_text='Marcar inactiva para dejar de usarla sin eliminarla', verbose_name='Activo')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Norma',
                'verbose_name_plural': 'Normas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PuntoNormaNC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('codigo', models.CharField(blank=True, help_text='Ej: 8.7, 7.1.5, Cap. 4', max_length=50, verbose_name='Código / Punto')),
                ('descripcion', models.CharField(help_text='Ej: Control de las salidas no conformes', max_length=255, verbose_name='Descripción del punto')),
                ('activo', models.BooleanField(default=True, help_text='Marcar inactivo para dejar de usarlo sin eliminarlo', verbose_name='Activo')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('norma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='nc.normanc', verbose_name='Norma')),
            ],
            options={
                'verbose_name': 'Punto de Norma',
                'verbose_name_plural': 'Puntos de Norma',
                'ordering': ['norma__nombre', 'codigo', 'descripcion'],
            },
        ),
        migrations.AddConstraint(
            model_name='puntonormanc',
            constraint=models.UniqueConstraint(fields=('norma', 'codigo', 'descripcion'), name='nc_puntonorman_unique_por_norma'),
        ),
        migrations.AddField(
            model_name='noconformidad',
            name='norma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='no_conformidades', to='nc.normanc', verbose_name='Norma'),
        ),
        migrations.AddField(
            model_name='noconformidad',
            name='punto_norma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='no_conformidades', to='nc.puntonormanc', verbose_name='Punto de la norma'),
        ),
    ]