# Generated by Django 6.0.4 on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0007_norma_nc_and_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='puntonormanc',
            name='nc_puntonorman_unique_por_norma',
        ),
        migrations.AddConstraint(
            model_name='puntonormanc',
            constraint=models.UniqueConstraint(
                fields=('norma', 'codigo', 'descripcion'),
                condition=models.Q(eliminado=False),
                name='nc_puntonorman_unique_por_norma',
            ),
        ),
    ]
