# Generated by Django 6.0.4 on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0008_update_punto_norma_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noconformidad',
            name='origen',
            field=models.CharField(
                choices=[
                    ('directo', 'Detección Directa'),
                    ('qr', 'Queja / Reclamo'),
                    ('om', 'Oportunidad de Mejora'),
                    ('aud_int', 'Auditoría Interna'),
                    ('aud_ext', 'Auditoría Externa'),
                ],
                default='directo',
                help_text='Origen de esta No Conformidad',
                max_length=10,
            ),
        ),
    ]
